language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: j0dEyJCFWPJo0hbSVIv2X25Kl5uNhQzeOAi9DUrJFFtetEHUs+5hYetHpXADXKPjPZ0+Vma9M7V8GiUj93O+G3Wp22qh6aLj2uvtCF2Cuqu6ztP8vr06vqEsDMyC0VihySk1fe6cy1YWdVGr1Rj4fEufYqlkDu5IUGyca5NspCBUTPJFm6VNi8mpwh98k/0q//FnmhfLK7GElS3tKotWr7ZX1kHVATcwUfG0cSAXEPbsXU/HDNxTHS2xOfm8A/eh5BJAq5XWZ49//4F9AbYwouy0eSTHzvVosazD8ckH1IN4Jh1F5XNvkxDrP9P5Xl5dIUuh91/VxT/1DzUkdgk+JA0J6z5O9HbzHl6qa9GYaBnOpu9J3b6PVIjeeM1HUclOr7eksOfnMMO7G4XL9ngJuGfARp2ED5QD8xm7nJTbZLy37zjjAKLl71VyMpfC797bjkGvANBwFs1j+UcxE4nko62inQ2rwpQABwAG3CWR0vvAvpx0/badHaJ4kNPejOW6c88fv/1fHk0xyPW9XH29FqrqJ5taY7Bct3HQEky6ciOIoo6CqN34yZ7+i9Khu6h1z86+nFMZZ0ULxLFFvTzp1As8oV0G6ZZGPIrMMZgHyGOxDv5aUxNxmA8hGN3DdrcmnrUsOBC0XfHhpdB54GioWdC8il/Rpsbt/6dAqrIxej0=
  app: p1xt-react-speedrun
