language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: pZZssAUZ1bPmcMeT0oHbIkHGTHIOHII1RlQ7O+mCXCbWgmetpey7fU5E8WWFvG/LODavNXvNBD5xoaUx41N3zC7f/yJLqjFy85K3lRplkXUPMCfY18Ctm2NZDDo0khIypncPQsUz61HLXzoWqhyymhv2wuJ20EIR3eh3k4281omuEd97KcBML4iUaDiwJZfXjJbWOUajMF1CskDI8XsytxoHPugP9Aju7sZSLicABdR6HOZRXmCPd5oD/KDDm4STkWJLRdUTS0+VBlWH7SpLEYzNtFHVK1ZYYYnbOZTN1NaxAug7/XBnyJ3H/G8q2aqfdlibGmC+pwirMudesKut/Vs5R73f5aREPRVN1sbrTGCg5c94xKIS7uwgaIoZLXL/mDmFmjLKru+F5DWPPsxP+dYQag3m2LUNMZwkuxoxbrabFDwJ0S/MMvxQbyBWigfNuWf+aBPwpcZCeyajNrnb6HXwVrtjZPrxjbf34yHwIElTCr6hj/ftxdjftTCtjOmG0wh4fAi5LlgpJu6aFXOGrk7kvLhKH+Z07udGH7cPmCXNSJxyurpiLMpnihArBwpO/LO2G0i45GXp4LuxCzGe4r88Qo31hXhlzfYD2P7e3yUESYBYGTHImGnmvQR9yvEwTrfZG/6XbgcSsXyNGlZOc9TK1rUkz+Rk5ATkRGdAchA=
  app: p1xt-react-speedrun
